# Generated by Django 4.2.9 on 2026-02-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_options_complaint_area_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
