# Generated by Django 5.2.11 on 2026-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='cleaned_image',
            field=models.ImageField(blank=True, null=True, upload_to='cleaned_proofs/'),
        ),
    ]
